In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [5]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [6]:
df = pd.read_csv("/content/titanic_data_updated.csv")

In [7]:
df.drop(['PassengerId', 'Name', 'Ticket', 'SibSp', 'Parch'], axis=1, inplace=True)

In [8]:
X = df.drop(["Survived"], axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
age_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
age_imputer.fit(X_train[["Age"]])
X_train['Age'] = age_imputer.transform(X_train[["Age"]]).ravel()
X_test['Age'] = age_imputer.transform(X_test[['Age']])
embarked_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
embarked_imputer.fit(X_train[['Embarked']])
X_train['Embarked'] = embarked_imputer.transform(X_train[['Embarked']]).ravel() # 2D ---> 1D
X_test['Embarked'] = embarked_imputer.transform(X_test[['Embarked']]).ravel() # 2D ---> 1D
cabin_imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='Missing', add_indicator=True)
cabin_imputer.fit(X_train[['Cabin']])
X_train[['Cabin', 'cabin_missing_indicator']] = cabin_imputer.transform(X_train[['Cabin']])
X_test[['Cabin', 'cabin_missing_indicator']] = cabin_imputer.transform(X_test[['Cabin']])

# Ordinal Encoder

In [9]:
pclass_encoder = OrdinalEncoder(categories=[['third', 'second', 'first']])
pclass_encoder.fit(X_train[['Pclass']])

X_train['Encoded_Pclass'] = pclass_encoder.transform(X_train[['Pclass']]).ravel()
X_test['Encoded_Pclass'] = pclass_encoder.transform(X_test[['Pclass']]).ravel()

# One-Hot Encoder

In [10]:
sex_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sex_ohe.fit(X_train[['Sex']])

encoded_df = sex_ohe.transform(X_train[['Sex']])
display(encoded_df)

X_train = pd.concat([X_train, encoded_df], axis=1)

X_train

     Sex_female  Sex_male
331         0.0       1.0
733         0.0       1.0
382         0.0       1.0
704         0.0       1.0
813         1.0       0.0
..          ...       ...
106         1.0       0.0
270         0.0       1.0
860         0.0       1.0
435         1.0       0.0
102         0.0       1.0

[712 rows x 2 columns]

,Pclass,Sex,Age,Fare,Cabin,Embarked,cabin_missing_indicator,Encoded_Pclass,Sex_female,Sex_male
331,first,male,45.500000,28.5000,C124,S,False,2.0,0.0,1.0
733,second,male,23.000000,13.0000,Missing,S,True,1.0,0.0,1.0
382,third,male,32.000000,7.9250,Missing,S,True,0.0,0.0,1.0
704,third,male,26.000000,7.8542,Missing,S,True,0.0,0.0,1.0
813,third,female,6.000000,31.2750,Missing,S,True,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,7.6500,Missing,S,True,0.0,1.0,0.0
270,first,male,29.498846,31.0000,Missing,S,True,2.0,0.0,1.0
860,third,male,41.000000,14.1083,Missing,S,True,0.0,0.0,1.0
435,first,female,14.000000,120.0000,B96 B98,S,False,2.0,1.0,0.0
102,first,male,21.000000,77.2875,D26,S,False,2.0,0.0,1.0

In [11]:
embarked_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
embarked_ohe.fit(X_train[['Embarked']])

encoded_df = embarked_ohe.transform(X_train[['Embarked']])
display(encoded_df)

X_train = pd.concat([X_train, encoded_df], axis=1)
X_train

     Embarked_C  Embarked_Q  Embarked_S
331         0.0         0.0         1.0
733         0.0         0.0         1.0
382         0.0         0.0         1.0
704         0.0         0.0         1.0
813         0.0         0.0         1.0
..          ...         ...         ...
106         0.0         0.0         1.0
270         0.0         0.0         1.0
860         0.0         0.0         1.0
435         0.0         0.0         1.0
102         0.0         0.0         1.0

[712 rows x 3 columns]

,Pclass,Sex,Age,Fare,Cabin,Embarked,cabin_missing_indicator,Encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
331,first,male,45.500000,28.5000,C124,S,False,2.0,0.0,1.0,0.0,0.0,1.0
733,second,male,23.000000,13.0000,Missing,S,True,1.0,0.0,1.0,0.0,0.0,1.0
382,third,male,32.000000,7.9250,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
704,third,male,26.000000,7.8542,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
813,third,female,6.000000,31.2750,Missing,S,True,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,7.6500,Missing,S,True,0.0,1.0,0.0,0.0,0.0,1.0
270,first,male,29.498846,31.0000,Missing,S,True,2.0,0.0,1.0,0.0,0.0,1.0
860,third,male,41.000000,14.1083,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
435,first,female,14.000000,120.0000,B96 B98,S,False,2.0,1.0,0.0,0.0,0.0,1.0
102,first,male,21.000000,77.2875,D26,S,False,2.0,0.0,1.0,0.0,0.0,1.0

In [12]:
X_train

,Pclass,Sex,Age,Fare,Cabin,Embarked,cabin_missing_indicator,Encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
331,first,male,45.500000,28.5000,C124,S,False,2.0,0.0,1.0,0.0,0.0,1.0
733,second,male,23.000000,13.0000,Missing,S,True,1.0,0.0,1.0,0.0,0.0,1.0
382,third,male,32.000000,7.9250,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
704,third,male,26.000000,7.8542,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
813,third,female,6.000000,31.2750,Missing,S,True,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,7.6500,Missing,S,True,0.0,1.0,0.0,0.0,0.0,1.0
270,first,male,29.498846,31.0000,Missing,S,True,2.0,0.0,1.0,0.0,0.0,1.0
860,third,male,41.000000,14.1083,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
435,first,female,14.000000,120.0000,B96 B98,S,False,2.0,1.0,0.0,0.0,0.0,1.0
102,first,male,21.000000,77.2875,D26,S,False,2.0,0.0,1.0,0.0,0.0,1.0

In [13]:
X_test

,Pclass,Sex,Age,Fare,Cabin,Embarked,cabin_missing_indicator,Encoded_Pclass
709,third,male,29.498846,15.2458,Missing,C,True,0.0
439,second,male,31.000000,10.5000,Missing,S,True,1.0
840,third,male,20.000000,7.9250,Missing,S,True,0.0
720,second,female,6.000000,33.0000,Missing,S,True,1.0
39,third,female,14.000000,11.2417,Missing,C,True,0.0
...,...,...,...,...,...,...,...,...
433,third,male,17.000000,7.1250,Missing,S,True,0.0
773,third,male,29.498846,7.2250,Missing,C,True,0.0
25,third,female,38.000000,31.3875,Missing,S,True,0.0
84,second,female,17.000000,10.5000,Missing,S,True,1.0
10,third,female,4.000000,16.7000,G6,S,False,0.0

In [14]:
encoded_df = sex_ohe.transform(X_test[['Sex']])
X_test = pd.concat([X_test, encoded_df], axis=1)

encoded_df = embarked_ohe.transform(X_test[['Embarked']])
X_test = pd.concat([X_test, encoded_df], axis=1)

In [15]:
X_test.drop(['Pclass', 'Sex', "Embarked"], axis=1, inplace=True)

In [16]:
X_train['Cabin_Deck'] = X_train['Cabin'].astype(str).str[0]
X_test['Cabin_Deck'] = X_test['Cabin'].astype(str).str[0]
X_train["Cabin_Deck"].value_counts()

Cabin_Deck
M    553
C     52
B     38
E     24
D     19
F     12
A     10
G      3
T      1
Name: count, dtype: int64

In [17]:
deck_ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
deck_ohe.fit(X_train[['Cabin_Deck']])

encoded_df = deck_ohe.transform(X_train[['Cabin_Deck']])
X_train = pd.concat([X_train, encoded_df], axis=1)

encoded_df = deck_ohe.transform(X_test[['Cabin_Deck']])
X_test = pd.concat([X_test, encoded_df], axis=1)

In [18]:
X_train.drop('Cabin_Deck', axis=1, inplace=True)
X_test.drop('Cabin_Deck', axis=1, inplace=True)

In [19]:
X_train

,Pclass,Sex,Age,Fare,Cabin,Embarked,cabin_missing_indicator,Encoded_Pclass,Sex_female,Sex_male,...,Embarked_Q,Embarked_S,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_M,Cabin_Deck_T
331,first,male,45.500000,28.5000,C124,S,False,2.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,second,male,23.000000,13.0000,Missing,S,True,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
382,third,male,32.000000,7.9250,Missing,S,True,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
704,third,male,26.000000,7.8542,Missing,S,True,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
813,third,female,6.000000,31.2750,Missing,S,True,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,7.6500,Missing,S,True,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
270,first,male,29.498846,31.0000,Missing,S,True,2.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
860,third,male,41.000000,14.1083,Missing,S,True,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
435,first,female,14.000000,120.0000,B96 B98,S,False,2.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,first,male,21.000000,77.2875,D26,S,False,2.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

# Label Encoding

In [23]:
y_train
type(y_train)

pandas.core.series.Series

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)
y_train_encoded = le.transform(y_train)
y_test_encoded = le.transform(y_test)

In [33]:
y_train_encoded
type(y_train_encoded)

pandas.core.series.Series

In [34]:
y_train_array = le.transform(y_train)
y_test_array = le.transform(y_test)

y_train = pd.Series(y_train_array, index=y_train.index, name=y_train.name)
y_test = pd.Series(y_test_array, index=y_test.index, name=y_test.name)

In [35]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64